// Known-answer tests for the ratchet's key schedule.
//
// Every other test in this suite is a round trip: encrypt with our code,
// decrypt with our code, check the plaintext survived. That proves the
// implementation agrees with itself, which a wrong implementation also does.
// Swap the two HMAC constants in KDF_CK, or feed HKDF the DH output as salt
// and the root key as IKM, and all of it still passes -- both sides make the
// same mistake in the same direction.
//
// These tests compare against `vectors.hpp`, generated by
// test/vectors/reference.py: the same derivations written from the
// specifications, in Python, without reference to src/ratchet.cpp. For a bug
// to survive here it would have to be made twice, independently, identically.

#include <cstdint>
#include <string>
#include <string_view>
#include <vector>

#include "ratchet/kdf.hpp"
#include "ratchet/message.hpp"
#include "ratchet/ratchet.hpp"
#include "ratchet/store.hpp"
#include "ratchet/x25519.hpp"
#include "test_support.hpp"
#include "vectors/vectors.hpp"

using namespace ratchet;
namespace rr = ::ratchet::ratchet;
namespace vec = ::ratchet::test::vectors;

namespace {

std::vector<uint8_t> unhex(std::string_view hex) {
  if (hex.size() % 2 != 0) {
    throw test::Failure("test vector has an odd number of hex digits");
  }
  std::vector<uint8_t> out;
  out.reserve(hex.size() / 2);
  for (std::size_t i = 0; i < hex.size(); i += 2) {
    auto nibble = [&](char c) -> uint8_t {
      if (c >= '0' && c <= '9') return static_cast<uint8_t>(c - '0');
      if (c >= 'a' && c <= 'f') return static_cast<uint8_t>(c - 'a' + 10);
      throw test::Failure("test vector has a non-hex digit");
    };
    out.push_back(static_cast<uint8_t>((nibble(hex[i]) << 4) | nibble(hex[i + 1])));
  }
  return out;
}

std::string hex_of(const uint8_t* p, std::size_t n) {
  static const char* digits = "0123456789abcdef";
  std::string out;
  out.reserve(n * 2);
  for (std::size_t i = 0; i < n; ++i) {
    out.push_back(digits[p[i] >> 4]);
    out.push_back(digits[p[i] & 0x0F]);
  }
  return out;
}

// Loads a 32-byte test vector into the secure buffer the ratchet API expects.
SecureBytes<32> key_from(std::string_view hex) {
  const std::vector<uint8_t> bytes = unhex(hex);
  if (bytes.size() != 32) {
    throw test::Failure("expected a 32-byte test vector");
  }
  SecureBytes<32> key;
  key.assign(bytes.data(), bytes.size());
  return key;
}

x25519::PublicKey pub_from(std::string_view hex) {
  const std::vector<uint8_t> bytes = unhex(hex);
  if (bytes.size() != x25519::kPublicBytes) {
    throw test::Failure("expected a 32-byte public key vector");
  }
  x25519::PublicKey pk{};
  std::copy(bytes.begin(), bytes.end(), pk.begin());
  return pk;
}

x25519::SecretKey secret_from(std::string_view hex) {
  const std::vector<uint8_t> bytes = unhex(hex);
  if (bytes.size() != x25519::kSecretBytes) {
    throw test::Failure("expected a 32-byte secret key vector");
  }
  x25519::SecretKey sk;
  sk.assign(bytes.data(), bytes.size());
  return sk;
}

// Compares a derived key against its expected value, reporting both in hex so
// a failure says what was produced rather than merely that it was wrong.
void expect_key(const SecureBytes<32>& got, std::string_view want, const char* what) {
  const std::string got_hex = hex_of(got.data(), got.size());
  if (got_hex != want) {
    throw test::Failure(std::string(what) + ": got " + got_hex + ", want " +
                        std::string(want));
  }
}

}  // namespace

TEST("vectors: the root-key info string matches the wire contract") {
  // A silent change here would fork the protocol: two builds would derive
  // different root keys from the same handshake and simply fail to talk.
  CHECK(rr::detail::kRootInfo == vec::kRootInfo);
}

TEST("vectors: KDF_CK matches the independent reference over five steps") {
  SecureBytes<32> ck = key_from(vec::kCkInitial);

  for (std::size_t step = 0; step < 5; ++step) {
    SecureBytes<32> next_ck;
    SecureBytes<32> mk;
    rr::detail::kdf_ck(ck, next_ck, mk);

    const std::string label = "chain key after step " + std::to_string(step);
    expect_key(next_ck, vec::kCkChain[step][0], label.c_str());
    const std::string mk_label = "message key at step " + std::to_string(step);
    expect_key(mk, vec::kCkChain[step][1], mk_label.c_str());

    ck = std::move(next_ck);
  }
}

TEST("vectors: KDF_CK's two constants are not interchangeable") {
  // The message key and the next chain key come from the same HMAC key and
  // differ only in a single input byte. If they ever came out equal, or if
  // the two were swapped, the ratchet would leak its own future.
  SecureBytes<32> ck = key_from(vec::kCkInitial);
  SecureBytes<32> next_ck;
  SecureBytes<32> mk;
  rr::detail::kdf_ck(ck, next_ck, mk);

  CHECK(hex_of(next_ck.data(), next_ck.size()) !=
        hex_of(mk.data(), mk.size()));
  // And specifically: the message key is not the *next* step's chain key.
  CHECK(hex_of(mk.data(), mk.size()) != std::string(vec::kCkChain[0][0]));
}

TEST("vectors: KDF_RK matches the independent reference") {
  const SecureBytes<32> rk = key_from(vec::kRkIn);
  const SecureBytes<32> dh_out = key_from(vec::kRkDhIn);

  SecureBytes<32> new_rk;
  SecureBytes<32> ck;
  rr::detail::kdf_rk(rk, dh_out, new_rk, ck);

  expect_key(new_rk, vec::kRkOut, "root key");
  expect_key(ck, vec::kRkCkOut, "chain key");
}

TEST("vectors: KDF_RK's salt and IKM are not interchangeable") {
  // HKDF-Extract(salt = root key, IKM = DH output) is the specified order.
  // Reversing it produces a schedule that round-trips perfectly and is wrong,
  // so pin that the two orders actually differ.
  const SecureBytes<32> rk = key_from(vec::kRkIn);
  const SecureBytes<32> dh_out = key_from(vec::kRkDhIn);

  kdf::Prk correct;
  kdf::extract(correct, rk.data(), rk.size(), dh_out.data(), dh_out.size());
  kdf::Prk reversed;
  kdf::extract(reversed, dh_out.data(), dh_out.size(), rk.data(), rk.size());

  CHECK(hex_of(correct.data(), correct.size()) !=
        hex_of(reversed.data(), reversed.size()));
}

TEST("vectors: KDF_RK is safe when its output aliases its input") {
  // src/ratchet.cpp calls kdf_rk(s.root_key, dh, s.root_key, s.chain_key_*),
  // so the root key is read and written through the same object. The result
  // must equal the non-aliased derivation.
  SecureBytes<32> rk = key_from(vec::kRkIn);
  const SecureBytes<32> dh_out = key_from(vec::kRkDhIn);

  SecureBytes<32> ck;
  rr::detail::kdf_rk(rk, dh_out, rk, ck);

  expect_key(rk, vec::kRkAliasOut, "aliased root key");
  expect_key(ck, vec::kRkAliasCk, "aliased chain key");
}

TEST("vectors: X25519 agrees with the independent reference") {
  const x25519::SecretKey alice_sk = secret_from(vec::kAliceEphSk);
  const x25519::PublicKey bob_pk = pub_from(vec::kBobSpkPk);

  SecureBytes<32> shared;
  x25519::dh(alice_sk, bob_pk, shared);
  expect_key(shared, vec::kDhAliceBob, "X25519 shared secret");

  // And the other direction lands on the same point.
  const x25519::SecretKey bob_sk = secret_from(vec::kBobSpkSk);
  const x25519::PublicKey alice_pk = pub_from(vec::kAliceEphPk);
  SecureBytes<32> shared_rev;
  x25519::dh(bob_sk, alice_pk, shared_rev);
  expect_key(shared_rev, vec::kDhAliceBob, "X25519 shared secret (reversed)");
}

TEST("vectors: a real session reaches the reference's root and chain keys") {
  // init_sender takes both of its key pairs as arguments, so Alice's side of
  // setup is fully deterministic -- the whole state after the handshake can be
  // compared against the reference, not just the primitives underneath it.
  store::Session s;
  rr::init_sender(s, key_from(vec::kSharedSecret), secret_from(vec::kAliceEphSk),
                  pub_from(vec::kAliceEphPk), pub_from(vec::kBobSpkPk));

  CHECK(s.has_cks);
  CHECK(!s.has_ckr);
  expect_key(s.root_key, vec::kSessionRootKey, "session root key");
  expect_key(s.chain_key_send, vec::kSessionCks0, "session sending chain key");
}

TEST("vectors: encrypting advances the sending chain exactly as specified") {
  store::Session s;
  rr::init_sender(s, key_from(vec::kSharedSecret), secret_from(vec::kAliceEphSk),
                  pub_from(vec::kAliceEphPk), pub_from(vec::kBobSpkPk));

  // Drive the real encrypt() path and check the chain key it leaves behind
  // after each message against the reference's chain. This ties the public
  // API to the vectors, not just the internal helpers.
  for (std::size_t i = 0; i < 3; ++i) {
    message::RatchetHeader header;
    std::vector<uint8_t> ciphertext;
    rr::encrypt(s, "message " + std::to_string(i), header, ciphertext);

    const std::string label = "sending chain key after message " + std::to_string(i);
    expect_key(s.chain_key_send, vec::kSessionSendingChain[i][0], label.c_str());
    CHECK_EQ(header.n, static_cast<uint32_t>(i));
    CHECK_EQ(header.pn, 0u);
  }
  CHECK_EQ(s.ns, 3u);
}

TEST("vectors: a DH ratchet step derives the reference's three keys") {
  // Replays the exact sequence dh_ratchet() performs -- receiving chain off
  // the current key pair, then a fresh pair, then the sending chain -- with
  // the fresh key pair supplied instead of generated, so the result is
  // reproducible.
  SecureBytes<32> root_key = key_from(vec::kSessionRootKey);
  const x25519::SecretKey bob_spk_sk = secret_from(vec::kBobSpkSk);
  const x25519::PublicKey alice_pk = pub_from(vec::kAliceEphPk);
  const x25519::SecretKey bob_next_sk = secret_from(vec::kBobNextSk);

  SecureBytes<32> dh_out;
  x25519::dh(bob_spk_sk, alice_pk, dh_out);
  SecureBytes<32> chain_key_recv;
  rr::detail::kdf_rk(root_key, dh_out, root_key, chain_key_recv);

  x25519::dh(bob_next_sk, alice_pk, dh_out);
  SecureBytes<32> chain_key_send;
  rr::detail::kdf_rk(root_key, dh_out, root_key, chain_key_send);

  expect_key(root_key, vec::kRatchetStepRk, "root key after DH ratchet");
  expect_key(chain_key_recv, vec::kRatchetStepCkr, "receiving chain key");
  expect_key(chain_key_send, vec::kRatchetStepCks, "sending chain key");
}

TEST("vectors: the header AAD is serialised exactly as specified") {
  // The AAD binds the ratchet header to the ciphertext. If its byte layout
  // drifted -- field order, or the endianness of the counters -- messages
  // would still round-trip locally while failing against any other build.
  message::RatchetHeader header;
  header.dh_pub = pub_from(vec::kAadDhPub);
  header.pn = vec::kAadPn;
  header.n = vec::kAadN;

  const std::vector<uint8_t> aad = message::header_aad(header);
  CHECK_EQ(hex_of(aad.data(), aad.size()), std::string(vec::kAad));
}

TEST("vectors: both HKDF paths produce the same bytes") {
  // The build uses libsodium's HKDF when available and its own RFC 5869
  // implementation otherwise. The vectors above were checked against whichever
  // path this build compiled in; this records which one that was, so a CI log
  // shows the fallback really was exercised somewhere.
  const SecureBytes<32> rk = key_from(vec::kRkIn);
  const SecureBytes<32> dh_out = key_from(vec::kRkDhIn);
  SecureBytes<32> new_rk;
  SecureBytes<32> ck;
  rr::detail::kdf_rk(rk, dh_out, new_rk, ck);

  expect_key(new_rk, vec::kRkOut,
             kdf::using_libsodium_hkdf() ? "root key (libsodium HKDF)"
                                         : "root key (fallback HKDF)");
}
