// Generated by test/vectors/reference.py -- do not edit by hand.
//
// Known-answer vectors for the ratchet's key schedule, produced by an
// independent implementation written from the specifications (RFC 7748,
// RFC 5869 and the Signal Double Ratchet's KDF construction) rather than from
// src/ratchet.cpp. A round-trip test proves the code agrees with itself; these
// prove it agrees with something that has never seen it.
//
// To regenerate:
//     python3 test/vectors/reference.py --emit > test/vectors/vectors.hpp
//
// CI regenerates this file and fails if the result differs from what is
// committed, so the two implementations cannot drift apart unnoticed.

#ifndef RATCHET_TEST_VECTORS_HPP
#define RATCHET_TEST_VECTORS_HPP

#include <cstdint>
#include <string_view>

namespace ratchet::test::vectors {

// --- KDF_CK: five consecutive symmetric ratchet steps ---
inline constexpr std::string_view kCkInitial =
    "32eac11865dde18b0359adda5429fd9f0763190aec4c26c4ee9bbd16dbd314a5";

inline constexpr std::string_view kCkChain[5][2] = {
    {"5abaf58370792d9115382c1b0609efb80860a6e8734f7a275e08994c043928db",
     "d0516ebea420237443a1ed0ad57a46a46420bc7bd99ef6151a28b80cda7a28d4"},
    {"4026628e61dc2bd4865d94c01ec9493574d01670545c6da39924904c8662791d",
     "dd2b60ce389bc0e6c3830f8566d3aab792a0cbe6e507955e584c3185d1c9cc61"},
    {"06fdeb6b9ef35d4fcbe2a321ab5c3bba13d559da0d4655128b327db12363636a",
     "417e00a6340ecbcde6bf11fadae72dc21228e2142faea5e2e75ef3d01903c463"},
    {"ae78d247a5082a5ca27b78e47e281abf1db59284778b90d2df80f9fbae91a8fa",
     "07876045719349842c1c1ff7acea53f1ecb07b5e28685a5758007de2fef5bae1"},
    {"ed338bd4a4dfbfd0840351d24d42f059b7a765034ab3d7a4eb22c596e37670bb",
     "8a6fe49e38b32d10229a4f397130e259a514b51c99f35bcdcc3c5786e63b9106"},
};

// --- KDF_RK: one DH ratchet step ---
inline constexpr std::string_view kRkIn =
    "a88b942edeb3117ae86495d34c69d9210a5a789f5cdf7184931c120ea86b2ae1";
inline constexpr std::string_view kRkDhIn =
    "ec3d3d87fc9f1e3139ab27788cea54205a46627fd03e144a725ba70afa950aed";
inline constexpr std::string_view kRkOut =
    "03ab3178e73fe140e136123e4270791a3411b4eb0f822b3ee9efb903bf7051b7";
inline constexpr std::string_view kRkCkOut =
    "4e0f5eace22c32f916f0d0278986733383041fe7d0cb1ea78b259649c4eab95e";
inline constexpr std::string_view kRkAliasOut =
    "03ab3178e73fe140e136123e4270791a3411b4eb0f822b3ee9efb903bf7051b7";
inline constexpr std::string_view kRkAliasCk =
    "4e0f5eace22c32f916f0d0278986733383041fe7d0cb1ea78b259649c4eab95e";

// --- Session setup, Alice's side ---
inline constexpr std::string_view kSharedSecret =
    "840c8443f057ede71e75eecc33c14db691620642febe3941116ccc4464ac672f";
inline constexpr std::string_view kAliceEphSk =
    "b8950bee8737f46ba8d136b2cdc28adba4e93e1771c8309b57d5479efd5e7b44";
inline constexpr std::string_view kAliceEphPk =
    "773a99121cce0ee0209c683f52fb6d968cf5609a7b2de1a6fb67a89bccd23728";
inline constexpr std::string_view kBobSpkSk =
    "6816afcd1f3bea4be49e277db36a5879a4253f11b796b57f6883765dab14356d";
inline constexpr std::string_view kBobSpkPk =
    "c8ef95bcc480a0129c2a73e9df3f030f0f1c346a2dc17972fd1033843348b070";
inline constexpr std::string_view kDhAliceBob =
    "8b2f798442ba0b249ac27b84fcdf9445af3b75b888ad22284f55d242a16ada5b";
inline constexpr std::string_view kSessionRootKey =
    "0705c89ebcf592fb90a6c7f82507af31827a1d5827545c57148afd58b0c0a4a4";
inline constexpr std::string_view kSessionCks0 =
    "7dcd0abfd6fb416144a4c6a0a4272026a17735c9b492414833231edab636538e";

inline constexpr std::string_view kSessionSendingChain[3][2] = {
    {"eb198b0ee17628a5d51ebb6938f99c22542edf2bb9cbf5815786a00d713d270e",
     "dca4c01692ab0b5cd3c652ad1bb9d87ba3987d77e4324d7849a22b1bb086445a"},
    {"9af3195d9118d7c0c3491ae89497dfa9bb60f73441ac467d77e2fa19b3f086a6",
     "059a93f0fa0c2430996087709a0b40ae85c709907c0f78c91633554b56fd69d0"},
    {"1c0cc99518906f0adfd356e2fd3c4587cf06366232ea1de5a47ffe96fbd676a3",
     "f2bb0981c308f208470a1f40b04df16cfa1765cb1098558f73fa4cbbb1b39432"},
};

// --- A full DH ratchet step ---
inline constexpr std::string_view kBobNextSk =
    "b0beb45fddf8e9adf429c5a0c8abf650a7766b78e8c51d4ee622ce76f25fe748";
inline constexpr std::string_view kBobNextPk =
    "4c7fffda472ee06154434702ae94e97db43b7b1567f06b0f1cfb5ec2c97ca82a";
inline constexpr std::string_view kRatchetStepRk =
    "bb92c8001550e4e80e58f0b7263f6958a4214e0283a4391bb22e446d18c1c34f";
inline constexpr std::string_view kRatchetStepCkr =
    "6b0bb0108fcfd88e097f516bd701aa0a54f024a5fb98eb2a12f828991ed81a65";
inline constexpr std::string_view kRatchetStepCks =
    "d0df25abe69fad19497fb0485c39a1609141075a9d5fc766ba704f01c0709373";

// --- Header associated data ---
inline constexpr std::string_view kAadDhPub =
    "773a99121cce0ee0209c683f52fb6d968cf5609a7b2de1a6fb67a89bccd23728";
inline constexpr uint32_t kAadPn = 16909060u;
inline constexpr uint32_t kAadN = 84281096u;
inline constexpr std::string_view kAad =
    "773a99121cce0ee0209c683f52fb6d968cf5609a7b2de1a6fb67a89bccd237280403020108070605";

// --- The wire-contract info string ---
inline constexpr std::string_view kRootInfo = "Ratchet-USB/v1/ratchet-root";

}  // namespace ratchet::test::vectors

#endif  // RATCHET_TEST_VECTORS_HPP
